
#
# Originally from Klöckner himself at:
#   https://github.com/conda-forge/staged-recipes/pull/1775
# This essentially swaps the dependency on the cuda toolkit to a conda feature.
# Also enables tests.
#
# This is needed by neon.
#

{% set name = "pycuda" %}
{% set version = "2020.1" %}
{% set sha256 = "effa3b99b55af67f3afba9b0d1b64b4a0add4dd6a33bdd6786df1aa4cc8761a5" %}

{% set cuda_version = "11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/46/61/47d3235a4c13eec5a5f03594ddb268f4858734e02980afbcd806e6242fa5/pycuda-2020.1.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # skip: true  # [not linux]
  script:
    - python configure.py --cuda-root=/usr/local/cuda/  # it would work magically anyway
    - python setup.py install --single-version-externally-managed --record record.txt
  features:
    - cuda{{ cuda_version }}
    - cuda{{ cuda_version }}dev  # no feature deps. in conda

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
  run:
    - python
    - numpy x.x
    - pytools
    - six
    - mako
    - appdirs

test:
  source_files:
    - test
  requires:
    - cuda-dev-feature {{ cuda_version }}
    - cuda-feature {{ cuda_version }}  # N.B. remove when cuda-dev-feature is able to track 2 features
    - pytest
    - pytools
    - six
    - mako
    - appdirs
  imports:
    - {{ name }}
  commands:
    # Nastily disabled because three tests fail with CUDA 8 / 1060.
    #   1- AttributeError: type object 'compute_mode' has no attribute 'EXCLUSIVE'
    #     Fixed upstream already: https://github.com/inducer/pycuda/issues/127
    #   2- Too large numeric errors (but still very small).
    #     I believe these are tests that need to be fixed to work on newer SW/HW.
    # - py.test test/

about:
  home: http://pypi.python.org/pypi/pycuda
  doc_url: https://documen.tician.de/pycuda
  dev_url: http://github.com/inducer/pycuda
  license: MIT
  license_file: doc/source/misc.rst
  # Can start using 'LICENSE' from next version
  summary: Python wrapper for CUDA
  description: |
    PyCUDA lets you access GPUs from Python, through the CUDA parallel
    compute interface.

extra:
  recipe-url: https://github.com/loopbio/pycuda-feedstock
  recipe-maintainers:
    - inducer (original)
    - sdvillal (loopbion changes)
